name: dorm_sqlite3
publish_to: none
description: SQLite3 database provider for Dorm
version: 1.0.0
author: David MARKEY

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^1.1.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ">=2.0.2"
  dorm:
    path: ../dorm

dev_dependencies:
  pedantic: ^1.10.0
